apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend-container
        image: shubhamdevops/frontend-app:latest
        env:
        - name: REACT_APP_BACKEND_URL
          value: http://backend-svc:8080
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
spec:
  type: NodePort              # expose on node port
  selector:
    app: frontend
  ports:
    - port: 3000              # ClusterIP port
      targetPort: 3000        # Pod port
      nodePort: 30300         # NodePort range 30000–32767
