apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-app-ingress
  namespace: default
  annotations:
    # Enable regex matching in paths
    nginx.ingress.kubernetes.io/use-regex: "true"
    # Strip the matched prefix (first capture group) before proxying
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  # Tell the cluster which IngressClass to use
  ingressClassName: nginx

  rules:
    - http:
        paths:
          # All /api/... → backend-svc:8080, with /api/ removed
          - path: /api/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: backend-svc
                port:
                  number: 8080

          # Everything else → react-frontend-svc:80, serving at root
          - path: /(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: react-frontend-svc
                port:
                  number: 80
